import React from 'react';
import { Dialog, DialogContent, IconButton, Typography, Box, Divider } from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';

const docText = `
Manage Portfolio
Welcome to the Manage Portfolio section of the CCA application. This guide will help you efficiently manage your cloud accounts by adding and updating instance details.

Note: All your actions and available features will be based on your assigned role.

The home page featuring tiles for different functionalities:

1. Manage Portfolio
2. Explorer
3. Download User Guide: Click the (📄) icon to download the CCA user guide.
4. Help section: Represented by the (?) icon, offers on-screen instructions and information about the current page.
5. Profile: Represented by the (👤) icon, displays the email ID of the logged-in user. To log out, click the icon and select the "Logout" option.

Adding Instances Individually
1. Select Cloud Service Provider: Choose the cloud service provider from the options (AWS , AZURE, GCP).
2. Enter Portfolio Name: Provide a name for your portfolio to identify it easily.
3. Update Instance Details:
   - UUID/Instance Name: A unique identifier or name assigned to an instance.
     For Ex: VM for AI/ML server. If not entered autogenerated UUID will be added
   - Region: Specify the geographical location where your cloud instances are deployed.
   - Size: Indicate the specifications or capacity of the cloud instance.
   - Quantity: Enter the number of instances for this configuration.
   - Total Number of Hours per Month:
     The total number of hours that all the instances (defined by the quantity) will be running during the month.
     To calculate the total hours, multiply the Quantity of instances by 730.
     Note: 730 is the total number of hours in a month.
     For example, if you have 5 instances, the Total Number of Hours per Month would be: Total Hours = 5 instances * 730 hours = 3650 hours/month.
   - Pricing Model: Select the pricing option for the instances (e.g., on demand, reserved or spot).
4. Add Instance: Click "+" Add Instance" to add the instance details to your portfolio.
5. Save Portfolio: Click "Save" to store your portfolio with the added instance details.
6. View Portfolios: After saving, you can view your portfolio in the portfolios list on the left side of the page.
7. View Instances: Click on any portfolio account from the list to view the instances saved under that portfolio.
8. Delete Instance: To delete an instance from the list, click on the delete icon (🗑️) next to the applicable instance row and the confirm the deletion.
9. Cancel: Click "Cancel" to discard the unsaved instances from the list.
10. Delete Portfolio: If you need to remove a portfolio, click on "Delete Portfolio".
11. Cost Advice: Click"Cost Advice" to receive recommendations on AMD instances compared to your current instances. This feature provides information on monthly and hourly costs, along with estimated total savings details if you switch to the recommended AMD instances.

Uploading Instances in Bulk
1. Download Template: Click on Template button to download the Excel template required for bulk uploading.
2. Fill in Template: Complete the template with instance details including uuid, cloud, region, size, quantity, Total Number of Hours per Month and Pricing Model.
3. Upload: Click "Upload" and browse for the completed template file to upload it.
4. View Uploaded Instances: After uploading, the instance details will be reflected in the table on the page.
5. Enter Portfolio Name: Provide a name for your new portfolio.
6. Save Portfolio: Click "Save" to store the portfolio with the uploaded instance details.
7. View Portfolios: After saving, you can see your portfolio in the portfolios list on the left side of the page.
8. View Instances: Click on any portfolio account from the list to view the instances saved under that portfolio.
9. Delete Instance: To delete an instance from the list, click on the delete icon (🗑️) next to the applicable instance row and the confirm the deletion.
10. Cancel: Click "Cancel" to discard the unsaved instances from the list.
11. Delete Portfolio: To delete a portfolio, click "Delete Portfolio".
12. Cost Advice: Click "Cost Advice" to receive recommendations on AMD instances compared to your current instances. This feature provides information on monthly and hourly costs, along with estimated total savings details if you switch to the recommended AMD instances.

Find & Replace:
Click(🔍) button to fix errors using the Find & Replace option.
From the Instance Type tab, select the invalid instance type that you want to change under the "From" dropdown, and select the correct instance type under the "To" dropdown.
From the Region tab, select the invalid region that you want to change under the "From" dropdown, and select the correct region under the "To" dropdown.
From the Pricing Model tab, select the invalid pricing model that you want to change under the "From" dropdown, and select the correct pricing model under the "To" dropdown.
Click Replace All. This will replace all selected invalid instance types, regions and pricing model with the chosen correct values.
Similarly, fix other invalid instance types , regions & and pricing model.
Once all errors are resolved, the "From" dropdown will show all available values in the table for instance types , pricing model & regions. The "To" dropdown will show all instance types and region values available for the selected CSP. You can find and replace any instance types or regions to the desired values.
Note: Double-click each field to update the values and correct the errors. The 'Save' and 'Cost Advice' buttons will remain disabled until all errors are resolved.

Delete Error Records:
To delete all the error records at once, click on the "Delete Error Records" button.
A confirmation popup will appear asking you to confirm the deletion.
To confirm, click the "Delete" button in the popup. This will remove all the error records from your list.
Click "Save" to apply changes. After saving, you can view the added portfolio in the portfolios list on the left side of the page.
`;

const OnlineDocumentationDialog = ({ open, onClose }) => (
  <Dialog
    open={open}
    onClose={onClose}
    PaperProps={{
      sx: {
        width: '1500px',
        maxWidth: '99vw',
        height: '90vh',
        maxHeight: '95vh',
      }
    }}
  >
    <DialogContent sx={{ maxHeight: '80vh', overflowY: 'auto', position: 'relative' }}>
      <Box display="flex" alignItems="center" mb={2}>
        <Typography variant="h6" sx={{ fontWeight: 700, fontSize: 24, flex: 1 }}>
          Manage Portfolio
        </Typography>
        <IconButton
          aria-label="close"
          onClick={onClose}
          sx={{ ml: 1 }}
        >
          <CloseIcon />
        </IconButton>
      </Box>
      <Divider sx={{ mb: 2 }} />
      <Typography component="div" sx={{ whiteSpace: 'pre-line', fontSize: 16 }}>
        {docText}
      </Typography>
    </DialogContent>
  </Dialog>
);

export default OnlineDocumentationDialog; 